name: Weather  Storage Gitactions

on: push 

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9.9'
    - name: Install python packages
      run:
        python -m pip install --upgrade pip
        pip install beautifulSoup4
        pip install requests
        pip install google-auth
        pip install google-cloud-storage

    - name: Execute py script
      run: python weather_storage.py
    